### PR TITLE
fix(application): fixes expose field handling

### LINKED ISSUE #917: Unable to expose single application endpoint
### Description

Attempting to specify a single value for `endpoints` in a `juju_application` resource's `expose` block results in a provider error:

`Unable to update application resource, got error: endpoint "endpoints" not found (not found)`

### Urgency

Casually reporting

### Terraform Juju Provider version

0.22.0

### Terraform version

1.12.2

### Juju version

3.6.9,3.5.7

### Terraform Configuration(s)

```terraform
terraform {
  required_version = ">= 1.6.6"
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "~> 0.22.0"
    }
  }
}
resource "juju_application" "haproxy" {
  name     = "haproxy"
  model    = "prod-canary-ps6-35"
  expose {
    endpoints = "website"
  }
  charm {
    name     = "haproxy"
    channel  = "2.8/edge"
    revision = 231
    base     = "ubuntu@24.04"
  }
}
```

### Reproduce / Test

```shell
terraform init
terraform apply
terraform apply
```

### Debug/Panic Output

```shell
prod-canary-ps6-35@is-bastion-ps6:~$ cat main.tf
terraform {
  required_version = ">= 1.6.6"
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "~> 0.22.0"
    }
  }
}
resource "juju_application" "haproxy" {
  name     = "haproxy"
  model    = "prod-canary-ps6-35"
  expose {
    endpoints = "website"
  }
  charm {
    name     = "haproxy"
    channel  = "2.8/edge"
    revision = 231
    base     = "ubuntu@24.04"
  }
}
prod-canary-ps6-35@is-bastion-ps6:~$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # juju_application.haproxy will be created
  + resource "juju_application" "haproxy" {
      + constraints = (known after apply)
      + id          = (known after apply)
      + machines    = (known after apply)
      + model       = "prod-canary-ps6-35"
      + model_type  = (known after apply)
      + name        = "haproxy"
      + placement   = (known after apply)
      + principal   = (known after apply)
      + storage     = (known after apply)
      + trust       = false
      + units       = 1

      + charm {
          + base     = "ubuntu@24.04"
          + channel  = "2.8/edge"
          + name     = "haproxy"
          + revision = 231
          + series   = (known after apply)
        }

      + expose {
          + endpoints = "website"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

juju_application.haproxy: Creating...
juju_application.haproxy: Creation complete after 2s [id=prod-canary-ps6-35:haproxy]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
prod-canary-ps6-35@is-bastion-ps6:~$ juju status
Model               Controller                         Cloud/Region           Version  SLA          Timestamp
prod-canary-ps6-35  juju-controller-35-production-ps6  prodstack6/prodstack6  3.5.7    unsupported  07:52:34Z

App      Version  Status   Scale  Charm    Channel   Rev  Exposed  Message
haproxy           waiting    0/1  haproxy  2.8/edge  231  yes      waiting for machine

Unit       Workload  Agent       Machine  Public address  Ports  Message
haproxy/0  waiting   allocating  4                               waiting for machine

Machine  State    Address  Inst id  Base          AZ  Message
4        pending           pending  ubuntu@24.04      starting
prod-canary-ps6-35@is-bastion-ps6:~$ terraform apply
juju_application.haproxy: Refreshing state... [id=prod-canary-ps6-35:haproxy]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # juju_application.haproxy will be updated in-place
  ~ resource "juju_application" "haproxy" {
        id          = "prod-canary-ps6-35:haproxy"
      ~ machines    = [
          - "4",
        ] -> (known after apply)
        name        = "haproxy"
      ~ placement   = "4" -> (known after apply)
      + principal   = (known after apply)
      + storage     = (known after apply)
        # (5 unchanged attributes hidden)

      ~ expose {
          ~ endpoints = ",website" -> "website"
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

juju_application.haproxy: Modifying... [id=prod-canary-ps6-35:haproxy]
╷
│ Error: Client Error
│
│   with juju_application.haproxy,
│   on main.tf line 10, in resource "juju_application" "haproxy":
│   10: resource "juju_application" "haproxy" {
│
│ Unable to update application resource, got error: endpoint "endpoints" not found (not found)
╵
prod-canary-ps6-35@is-bastion-ps6:~$
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by alesstimec**
## Description

Fixes the exposing and unexposing endpoints in `juju_application`.

fix #917

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## QA steps

Manual QA steps should be done to test this PR.

1. Create a terraform plan:
```tf
terraform {
  required_providers {
    juju = {
      source = "juju/juju"
      version = "1.0.0"
    }
  }
}

provider "juju" {}

resource "juju_model" "this" {
  name = "test"
}

resource "juju_application" "app" {
  name     = "app"
  model_uuid    = juju_model.this.uuid
  expose {
    endpoints = "website"
  }
  charm {
    name     = "apache2"
    channel  = "latest/stable"
    revision = 64
    base     = "ubuntu@22.04"
  }
}
```
2. apply the plan
3. change `endpoints` to "website,apache-website"
4. apply the plan
5. change `endpoints` to "apache-website,website"
6. run `terraform plan` and no changes should be planned

### CODE REVIEW

File: internal/provider/resource_application_test.go [hunk 1]
```diff
@@ -97,6 +97,70 @@ func TestAcc_ResourceApplication(t *testing.T) {
...
+    name     = "apache2"
+    channel  = "latest/stable"
+    revision = 64
+    base     = "ubuntu@22.04"
+  }
+}
+		`, modelName, endpoints)
+}
+
+func TestAcc_ResourceApplication_Expose(t *testing.T) {
```
Comment (SimoneDutto) [inline internal/provider/resource_application_test.go]: this test is not testing the no update for the comma separate sorted list. Right?

File: internal/provider/custom_type_csv_string_test.go [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+		for i := range 2 {
+			// Reverse the order for the second iteration
+			// to test both directions of comparison.
+			var name string
+			if i == 0 {
+				name = tt.name + "/forward"
+			} else {
+				name = tt.name + "/reverse"
+				left, right = right, left // swap for reverse test
+			}
```
[the remark this answers is not in the document]
Comment (alesstimec) [reply internal/provider/custom_type_csv_string_test.go]: removed the extra logic as it did not test anything extra

File: internal/provider/custom_type_csv_string.go [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+
+	if len(leftTokens) != len(rightTokens) {
+		return false, diags
+	}
+
+	slices.Sort(leftTokens)
+	slices.Sort(rightTokens)
+
+	equal := slices.Equal(leftTokens, rightTokens)
+	return equal, diags
```
[the remark this answers is not in the document]
Comment (alesstimec) [reply internal/provider/custom_type_csv_string.go]: done

File: internal/provider/resource_application.go [hunk 4]
```diff
@@ -1355,27 +1361,48 @@ func (r *applicationResource) computeExposeDeltas(ctx context.Context, stateExpo
 		return nil, []string{}, diags
 	}
 
-	toExpose := make(map[string]interface{})
-	toUnexpose := make([]string, 0)
+	planEndpoints := strings.Split(planNestedExpose[0].Endpoints.ValueString(), ",")
```
Comment (kian99) [inline internal/provider/resource_application.go]: Reading this makes me realise the schema for `expose` is slightly wrong, it shouldn't be a list of nested objects, just a single nested object. We only ever seem to use the first item from the list anyway. Maybe we can fix this in here as well before we release 1.0?

Comment (alesstimec) [reply internal/provider/resource_application.go]: this will not land in time for 1.0

Comment (alesstimec) [reply internal/provider/resource_application.go]: but i do agree the schema for expose is wrong..
