### PR TITLE
feat: fix defaults being sent down from juju when nothing is specifie…

### LINKED ISSUE #1119: juju_machine: "Provider produced inconsistent result after apply" with root-disk-source=volume constraint
## Description

When a `juju_machine` resource has `constraints` set to a value containing `root-disk-source=volume`, Terraform errors on every apply with:

```
Error: Provider produced inconsistent result after apply

When applying changes to module.landscape_scalable.juju_machine.landscape_server[0], provider
"provider["registry.terraform.io/juju/juju"]" produced an unexpected new value: .constraints: was null,
but now cty.StringVal("root-disk-source=volume").

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

The provider reads back the constraints after apply and gets `root-disk-source=volume` from Juju, but the planned value was `null` (because the constraint was not set in the TF config — it was set in the underlying module). This causes every apply to fail on this resource.

## Urgency

Blocker for our release

## Terraform Juju Provider version

1.0.0

## Terraform version

```
Terraform v1.11.2
on linux_amd64
```

## Juju version

3.6.12

## Terraform Configuration(s)

```terraform
resource "juju_machine" "landscape_server" {
  model_uuid  = var.model_uuid
  name        = "landscape-server-0"
  constraints = "root-disk-source=volume"
  base        = "ubuntu@24.04"
}
```

The error occurs even when `constraints` is set explicitly in config — Juju returns the constraint after apply but the provider treats the planned value as `null` and then sees a diff.

## Reproduce / Test

```shell
terraform apply   # succeeds first time
terraform apply   # fails with "Provider produced inconsistent result after apply: .constraints: was null, but now cty.StringVal("root-disk-source=volume")"
```

## Debug/Panic Output

```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.landscape_scalable.juju_machine.landscape_server[0], provider
│ "provider["registry.terraform.io/juju/juju"]" produced an unexpected new value: .constraints: was null,
│ but now cty.StringVal("root-disk-source=volume").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

## Notes & References

The `root-disk-source=volume` constraint appears to be a Juju-side constraint that gets stored and returned but the provider does not preserve it in state after the initial apply, causing a perpetual diff. Related to but distinct from #443 (which is about `placement`, not `constraints`).

### PR DESCRIPTION
**Pull request by ale8k**
…d for constraints

## Description

Fixes juju_machine.constraints state inconsistency when constraints come from model defaults rather than being set directly on the machine.

Opened a new PR and closed #1124 

After discussions, we're just simply making it computed and using Juju for the unknown now. If agreed, this will become our usual approach to handling defaults.

There is a bit of discomfort with this approach though, when creating the model with a constraint of "1G" for memory, and then subsequently reading the machine to see what its memory constraint is set to, Juju normalises it into "1024M". As such TF is signalling an update like so:

```tf
Terraform will perform the following actions:

  # juju_model.test will be updated in-place
  ~ resource "juju_model" "test" {
      ~ constraints = "arch=arm64 mem=1024M" -> "arch=arm64 mem=1G"
        id          = "bdee015e-e082-4ff5-8af5-cb05a50282eb"
        name        = "test"
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

There's another little nuance, if you change the models constraints, and apply the plan again, you will see:
```tf
Terraform will perform the following actions:

  # juju_model.test will be updated in-place
  ~ resource "juju_model" "test" {
      ~ constraints = "arch=arm64 mem=1024M" -> "arch=arm64 mem=512M"
        id          = "bdee015e-e082-4ff5-8af5-cb05a50282eb"
        name        = "test"
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Which it obviously isn't changing the memory on the machine - so perhaps this is misleading.

It is functionally harmless and merely noise, my question is, is it worth adding noise reduction logic for scenarios like this? 

Lastly, we normalise empty machine constraint values to null in state, instead of storing them as an empty string, and applies that consistently across create, read, and import. This avoids mismatches where the same unset value could appear differently between lifecycle paths, which in turn removes false drift/import verification noise.

Fixes: #1119 

## Type of change

- Change existing resource

## Environment

- Juju controller version: 3.6.X

- Terraform version: 1.14

## QA steps

Run this plan twice.
```tf
terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "1.3.0"
    }
  }
}

resource "juju_model" "test" {
  name = "test"
  constraints = "arch=arm64 mem=1G"
}

resource "juju_machine" "landscape_server" {
  model_uuid  = juju_model.test.uuid
  name        = "landscape-server-0"
  base        = "ubuntu@24.04"
}
```

### CODE REVIEW

**Review by alesstimec — CHANGES_REQUESTED** [review]
Can you please add a test that would validate this approach?

**Comment by ale8k** [comment]
> Can you please add a test that would validate this approach?

Yup can do, just fixing another side of this first regarding imports.

**Review by alesstimec — APPROVED** [review]

File: internal/provider/resource_machine.go [hunk 1]
```diff
@@ -388,6 +389,9 @@ func (r *machineResource) Create(ctx context.Context, req resource.CreateRequest
 
 	plan.Base = types.StringValue(readResponse.Base)
 	plan.Hostname = types.StringValue(readResponse.Hostname)
+	if plan.Constraints.IsUnknown() {
+		plan.Constraints = NewNormalizedCustomConstraintsValue(readResponse.Constraints)
+	}
```
Comment (kian99) [inline internal/provider/resource_machine.go]: Why only set plan.Constraints if it is unknown?

File: internal/provider/resource_machine_test.go [hunk 2]
```diff
@@ -360,6 +360,32 @@ func TestAcc_ResourceMachine_ConstraintsNormalization(t *testing.T) {
...
+				Config: testAccResourceMachineWithModelConstraints(modelName, "mem=512M"),
+				Check: resource.ComposeTestCheckFunc(
+					resource.TestCheckResourceAttrPair("juju_model.this", "uuid", resourceName, "model_uuid"),
+					resource.TestCheckResourceAttr(resourceName, "name", "this_machine"),
+					resource.TestCheckResourceAttrSet(resourceName, "constraints"),
+				),
+			},
+			{
+				Config:   testAccResourceMachineWithModelConstraints(modelName, "mem=512M"),
+				PlanOnly: true,
```
Comment (kian99) [inline internal/provider/resource_machine_test.go]: The point of this step is to check that it doesn't cause an error right? Can you leave a comment to that effect

File: internal/provider/resource_machine.go (hunk 1 above)
Comment (ale8k) [reply internal/provider/resource_machine.go]: So we only populate it from Juju if the user hasn't explicitly set it, and if they haven't, we take the Juju response (like we agreed would be our approach), otherwise it'll set what is in plan (what the user set).

File: internal/provider/resource_machine_test.go (hunk 2 above)
Comment (ale8k) [reply internal/provider/resource_machine_test.go]: Yup, just proves we don't get any drift (i.e., Juju normalising it from M), and because it was user set, we expect it to stay user set. If it is Juju set, it'll hit the unknown path and should always work given Juju responds the same. 

I'll add a comment explaining this.

File: internal/provider/resource_machine.go (hunk 1 above)
Comment (ale8k) [reply internal/provider/resource_machine.go]: As discussed resolved.

**Review by kian99 — APPROVED** [review]
