### PR TITLE
fix: allow last key to be deleted

### LINKED ISSUE #1163: Removing juju_ssh_key resources doesn't actually remove SSH keys from the model
### Description

During rework of a terraform module's juju_ssh_key clauses, I hit some "duplicate SSH key" errors.

I first hit this because of changing from a single juju_ssh_key resource to a version which uses a for_each loop over a set.  Changing from a single explicit juju_ssh_key resource to a for_each loop containing the same key hits this error.

However, additionally, I found that even just removing the juju_ssh_key clause resulted in it being removed from the Terraform state, but not actually removed from the Juju model.  If I wanted to re-add the same SSH key, I would have to manually remove the SSH key via the Juju CLI, after which I could re-apply the key via Terraform.

### Urgency

Casually reporting

### Terraform Juju Provider version

1.3.1

### Terraform version

1.14.8

### Juju version

3.6.12

### Terraform Configuration(s)

```terraform
# Dependency: data.juju_model.this, pointing to an existing Juju model
#
# You can apply this snippet to add my SSH pubkey - but don't; use your own! - and
# then comment out to remove the same.  However, again, the key won't actually be
# removed from the model; `juju list-ssh-keys -m $MODEL` will still show the key as
# being present.

resource "juju_ssh_key" "key_set" {
  for_each = toset([
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPSihXipogdMY70BaZX+owOOi1nBnIYDpDr6iQHIZtE4 paul-goins@rog2023", # vultaire
  ])
  model_uuid = data.juju_model.this.uuid
  payload    = each.value
}
```

### Reproduce / Test

```shell
See the comments with the Terraform snippet.
```

### Debug/Panic Output

```shell
N/A; Terraform does not error.
```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by ale8k**
## Description
We were preventing the last key to be deleted, but as far as I can tell, in both 2.9 and 3.6, it is now possible to delete the last key as the system key is always present within the model, but not visible.

After a short discussion with Joe, he believes:
```
I don't know that it's possible to hit this bug. On both 2.9 and 3.6 I can add and delete the (reportedly last) key, and still ssh to a machine.

The semantic guard dates from very early days, ~2013.
```

I believe I've hit in 3.6 before, but after testing I cannot reproduce it. So I **think** we are safe to remove it. 

Fixes: #1163 

## Type of change

- Logic changes in resources (the API interaction with Juju has been changed)

## Environment

- Juju controller version: 3.6.14

- Terraform version: 1.14.9

## QA steps

Run:
`make install`

On a 3.6 controller run:
`jj add-model issue1163`

Then:
`jj show-model issue1163` 
And extract the model uuid.

Run:
`jj ssh-keys`
And verify there are no keys.

Apply this plan (update datasource model uuid), and then destroy it.
```tf
terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "1.3.1"
    }
  }
}


data "juju_model" "this" {
  uuid = "cc7f0959-155c-468c-8628-7971ef328761"
}
resource "juju_ssh_key" "key_set" {
  model_uuid = data.juju_model.this.uuid
  payload    = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPSihXipogdMY70BaZX+owOOi1nBnIYDpDr6iQHIZtE4 blah@blah"
}
```

Run:
`jj ssh-keys`
You should see your blah blah key.

Run:
`tf destroy`

Run:
`jj ssh-keys`
And verify the key is gone.

### CODE REVIEW

**Review by luci1900 — APPROVED** [review]

**Review by SimoneDutto — COMMENTED** [review]
i vividly remember hitting this bug and the reason why we need this piece of code.

Can you double check in git history if there is a specific reproducer and a reason behind this?

**Comment by ale8k** [comment]
> i vividly remember hitting this bug and the reason why we need this piece of code.
> 
> Can you double check in git history if there is a specific reproducer and a reason behind this?

I did, it was by Cedric and he created a Juju bug in 2.9 for it. See my resp ehre: https://github.com/juju/terraform-provider-juju/issues/1163#issuecomment-4260251619

File: internal/provider/resource_ssh_key_test.go [hunk 1]
```diff
@@ -197,6 +205,49 @@ func TestAcc_ResourceSSHKey_UpgradeV0ToV1(t *testing.T) {
 	})
 }
 
+func testAccCheckSSHKeyAbsent(modelName string, payload string) resource.TestCheckFunc {
```
Comment (SimoneDutto) [inline internal/provider/resource_ssh_key_test.go:208]: if the Read method works as expected, you don't need this specific check right?

**Review by SimoneDutto — COMMENTED** [review]
i'm happy to approve, because it seems you did the right amount of vetting

**Review by SimoneDutto — APPROVED** [review]

File: internal/provider/resource_ssh_key_test.go (hunk 1 above)
Comment (ale8k) [reply internal/provider/resource_ssh_key_test.go:208]: As discussed, Ales' requested it. Does no harm really either I guess.
