### PR TITLE
[JUJU-3863] Process region value in cloud models and force it to be computed

### LINKED ISSUE #209: terraform reports region value update which doesn't get resolved on apply.
Terraform reports update to model that doesn't get resolved after applying.  It always wants to remove the region key, although it was not included in the tf file.

### Terraform Version

```
Terraform v1.4.6
on linux_amd64
```

### Affected Resource(s)

- `juju_model`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    juju = {
      version = "~> 0.7.0"
      source  = "juju/juju"
    }
  }
}


provider "juju" {}

resource "juju_model" "terraform" {
  name = "terraform"

  cloud {
    name   = "localhost"
  }
}
```

### Panic Output

NA

### Expected Behavior

no changes reported

### Actual Behavior

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # juju_model.terraform will be updated in-place
  ~ resource "juju_model" "terraform" {
        id         = "b86dbd3b-07ec-4283-8019-dc99903142ac"
        name       = "terraform"
        # (3 unchanged attributes hidden)

      ~ cloud {
            name   = "localhost"
          - region = "localhost" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`
3. `terraform apply`

Note that the change is never resolved.

### Important Factoids

- lxd localhost cloud, juju 3.1.2

### References

NA

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
## Description

The `region` parameter in the `cloud` section from the `resource_model` should be computed by the provider when empty. In this manner, something like:

```tf
resource "juju_model" "terraform" {
  name = "terraform"
  cloud {
    name   = "localhost"
  }
}
```

will automatically set the `region` value to be `localhost` which is the default value returned by the Juju provider.

Fix #209 

## Type of change

Please mark if proceeds.

- [ ] New resource (a new resource in the schema)
- [x] Changed resource (changes in an existing resource)
- [ ] Logic changes in resources (the API interaction with Juju has been changed)
- [ ] Test changes (one or several tests have been changed)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other (describe)

## Environment

- Juju controller version: 2.9.42
- Terraform version: 1.36

## QA steps

Try to apply the plan described in #209 twice. No new values are detected now.

```tf
terraform {
  required_providers {
    juju = {
      version = "~> 0.7.0"
      source  = "juju/juju"
    }
  }
}


provider "juju" {}

resource "juju_model" "terraform" {
  name = "terraform"

  cloud {
    name   = "localhost"
  }
}
```

```sh
terraform init
terraform apply --auto-approve
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # juju_model.terraform will be created
  + resource "juju_model" "terraform" {
      + credential = (known after apply)
      + id         = (known after apply)
      + name       = "terraform"
      + type       = (known after apply)

      + cloud {
          + name   = "localhost"
          + region = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
juju_model.terraform: Creating...
juju_model.terraform: Creation complete after 6s [id=77a75e5b-1236-48b5-8564-6c234f36767e]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
terraform apply --auto-approve
juju_model.terraform: Refreshing state... [id=77a75e5b-1236-48b5-8564-6c234f36767e]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are
needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### CODE REVIEW

File: internal/provider/resource_model.go [hunk 1]
```diff
@@ -110,9 +111,37 @@ func resourceModelCreate(ctx context.Context, d *schema.ResourceData, meta inter
 		return diag.FromErr(err)
 	}
 
-	// TODO: If cloud is blank, we should set it to the default (returned in modelInfo)
+	// compute the cloud information required
+	var cloudNameInput, cloudRegionInput string = "", ""
+	for _, c := range cloud {
+		cloudEntry := c.(map[string]interface{})
+		cloudNameInput = cloudEntry["name"].(string)
+		cloudRegionInput = cloudEntry["region"].(string)
```
Comment (cderici) [inline internal/provider/resource_model.go:119]: Is this part of the code dead?  `cloud` is set on `d` below only when the `cloudChanged` is true, and that happens only when either `cloudNameInput == ""` or `cloudRegionInput == ""`.

**Review by cderici — APPROVED** [review]
LGTM (modulo a possible fix required in code), QA went well 👍
