### PR TITLE
[JUJU-2639] Fix error when setting model constraints.

### LINKED ISSUE #109: Ability to add machine constraints to units.
Ability to add machine constraints to units.

Currently, I cannot see this possible. The minimum of CpuCores, Mem and RootDisk would be nice.

Thanks.

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
This PR fixes #109 

Erroneously during the model creation the model config client was establishing a connection with the controller instead of the new model.

## QA
Bootstrap a controller and run the following plan.
```

provider "juju" {}

resource "juju_model" "development" {
  name = "development"

  constraints = "mem=1024M"
}

resource "juju_application" "ubuntu" {
  name = "ubuntu"

  model = juju_model.development.name

  charm {
    name = "ubuntu"
  }
}
```
Next, check that the model constraints are correct.
```
juju model-constraints -m development
mem=1024M
```

### CODE REVIEW

File: internal/juju/models.go [hunk 1]
```diff
@@ -165,12 +165,18 @@ func (c *modelsClient) CreateModel(input CreateModelInput) (*CreateModelResponse
...
 	// set constraints when required
-	if input.Constraints.String() != "" {
+	if input.Constraints.String() == "" {
 		return &CreateModelResponse{ModelInfo: modelInfo}, nil
 	}
 
-	// we have to set constraints
-	modelClient := modelconfig.NewClient(conn)
+	// we have to set constraints ...
+	// stablish a new connection with the target model and set constraints
```
Comment (cderici) [inline internal/juju/models.go:173]: this comment seems a bit confusing

```suggestion
	// establish a new connection with the created model through the modelconfig api to set constraints
```

**Review by cderici — APPROVED** [review]
LGTM. QA steps confirmed :+1:
