### PR TITLE
[JUJU-3315] Force "stable" channel to be "latest/stable" when reading apps.

### LINKED ISSUE #113: `terraform import` of postgresql-k8s charm incorrectly recognises channel
### Terraform Version
```
Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.4.3
```
### Affected Resource(s)
- juju_application
### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.4.3"
    }
  }
}
provider "juju" {}

resource "juju_model" "test" {
  name = "pgtest"
}

resource "juju_application" "postgresql_k8s" {
  name  = "postgresql"
  model = juju_model.test.name

  charm {
    name = "postgresql-k8s"
  }

  units = 1
}
```

### Debug Output
N/A
### Panic Output
N/A

### Expected Behavior
I did the following:
```
# Bootstrap a juju controller on microk8s 1.25 with juju 2.9.37
juju add-model pgtest
juju deploy postgresql-k8s postgresql
terraform import juju_model.test pgtest
terraform import juju_application.postgresql_k8s pgtest:postgresql
terraform plan
```
I would expect the output to be "no changes" based on the hcl file above.
### Actual Behavior
When I ran `terraform plan` I got the following:
```
$ terraform plan
juju_model.test: Refreshing state... [id=d6114340-9c0d-46c3-8eda-ee3113384e34]
juju_application.postgresql_k8s: Refreshing state... [id=pgtest:postgresql]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # juju_application.postgresql_k8s will be updated in-place
  ~ resource "juju_application" "postgresql_k8s" {
        id    = "pgtest:postgresql"
        name  = "postgresql"
        # (3 unchanged attributes hidden)

      ~ charm {
          ~ channel  = "stable" -> "latest/stable"
            name     = "postgresql-k8s"
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

### Steps to Reproduce
See above.

### Important Factoids
N/A
### References
N/A

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
## Description

Depending on how a charm is uploaded to CharmHub, Juju may resolve the channel to be `stable` instead of `latest/stable`. This leads to awkward situations where Terraform things the state has changed as reported in #113. This PR forces the `stable` channel to be replaced by `latest/stable` when reading applications. 

Fix #113.

## Type of change

Please mark if proceeds.

- [ ] New resource (a new resource in the schema)
- [ ] Changed resource (changes in an existing resource)
- [ ] Logic changes in resources (the API interaction with Juju has been changed)
- [ ] Test changes (one or several tests have been changed)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other (describe)

## Environment

- Juju controller version: 2.9.42
- Terraform version: 1.4.6

## QA steps

The steps reported in #113 are no longer valid to reproduce this issue after the last changes in the postgresql-k8s charm. A similar scenario can be reproduced using the github-runner charm.

Deploy the github-runner charm

```sh
juju bootstrap microk8s datest
juju add-model ghrunner
juju deploy github-runner ghrunner
```
Create a plan and import the model and the application

```tf
terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "1.0.0"
    }
  }
}

provider "juju" {}

resource "juju_model" "ghrunner" {
  name = "ghrunnertest"
}

resource "juju_application" "ghrunner" {
  name  = "ghrunner"
  model = juju_model.ghrunner.name

  charm {
    name = "github-runner"
  }

  units = 1
}
```

```sh
terraform init -plugin-dir=<wherever your compiled providers are>
terraform import juju_model.ghrunner ghrunner
terraform import terraform import juju_application.ghrunner ghrunner:ghrunner
```
Terraform should not detect any changes
```sh
terraform plan

juju_model.ghrunner: Refreshing state... [id=08552cd9-4e03-40d5-8a3a-3d6f09faee7f]
juju_application.ghrunner: Refreshing state... [id=ghrunner:ghrunner]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

If the same steps are done with the 0.6.0 controller, Terraform finds changes to be done.
```sh
terraform plan
juju_model.ghrunner: Refreshing state... [id=08552cd9-4e03-40d5-8a3a-3d6f09faee7f]
juju_application.ghrunner: Refreshing state... [id=ghrunner:ghrunner]

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # juju_application.ghrunner will be updated in-place
  ~ resource "juju_application" "ghrunner" {
        id          = "ghrunner:ghrunner"
        name        = "ghrunner"
        # (5 unchanged attributes hidden)

      ~ charm {
          ~ channel  = "stable" -> "latest/stable"
            name     = "github-runner"
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

### CODE REVIEW

File: internal/juju/applications.go [hunk 1]
```diff
@@ -637,9 +637,18 @@ func (c applicationsClient) ReadApplication(input *ReadApplicationInput) (*ReadA
 		exposed["cidrs"] = cidrs
 	}
 
+	// (juanmanuel-tirado) In certain scenarios depending on how
+	// charms are uploaded to CharmHub, Juju may register the
+	// latest/stable channel as stable. We check this case here
+	// and force it to be latest/stable
+	normalizedChannel := appInfo.Channel
+	if normalizedChannel == "stable" {
+		normalizedChannel = "latest/stable"
```
Comment (cderici) [inline internal/juju/applications.go:646]: This seems incorrect. We shouldn't need to coerce the track in the client. The app is deployed with the channel `stable` and `ReadApplication` (`applicationAPIClient.ApplicationsInfo` really) is correctly bringing the channel as `stable`. I think the problem is we [incorrectly default to `latest/stable`](https://github.com/juju/terraform-provider-juju/blob/a4a7e437300b57ae2df2583a864a979d15a2ca53/internal/provider/resource_application.go#LL56C1-L56C13) when a channel is not specified. I believe the correct fix is defaulting to just `stable` instead of fixating the track as well.

**Review by cderici — CHANGES_REQUESTED** [review]

**Comment by juanmanuel-tirado** [comment]
I gave it a second thought. I think this approach makes more sense. We will make the `channel` field to be computed so the value is decided during the deployment phase. If by the time we create an application the `channel` is empty, we will force it to be `stable`.

**Review by cderici — APPROVED** [review]
Yeah I think this is correct :+1: we should probably remove [that defaulting to the latest/stable](https://github.com/juju/terraform-provider-juju/blob/a4a7e437300b57ae2df2583a864a979d15a2ca53/internal/provider/resource_application.go#LL56C1-L56C13) at some point as well.
