### PR TITLE
fix(remove-machine): when a machine is removed we should remove units

### LINKED ISSUE #1189: Unable to scale-down by destroying a machine (which has units running on it)
### Description

I have a an app of multiple juju units, each already running on a machine on a manual-cloud model. I am trying to scale down by removing one machine

I have an array of ips in tfvars. I removed one of the ips from the array  then ran `terraform apply`. terraform tries first to destroy the machine then to update in-place the juu app (i.e. removing a unit) . So terraform gets stuck in destroying the machine. Same timeout occurs when using partial apply (on the juju_application) and/or when using create_before_destroy which is suggested in the [documentation](https://registry.terraform.io/providers/juju/juju/latest/docs/resources/machine)

in juju cli world, it will just be `juju remove-machine ---force` to handle removing the running units as well

### Urgency

Blocker for our release

### Terraform Juju Provider version

1.1.0

### Terraform version

Terraform v1.10.5-dev on linux_amd64

### Juju version

3.6.2

### Terraform Configuration(s)
Assuming a controller ( with manual cloud ) already exists
```terraform
resource "juju_model" "k8s" {
  name = var.K8S_MODEL

  cloud {
    name = var.K8S_CLOUD
  }

}
resource "juju_machine" "workers" {
  count = length(var.K8S_WORKER)

  model_uuid = juju_model.k8s.uuid
  ssh_address      = "ubuntu@${var.K8S_WORKER[count.index]}"
  public_key_file  = pathexpand("~/.ssh/id_rsa.pub")
  private_key_file = pathexpand("~/.ssh/id_rsa")

  # If you face timeouts destroying machines, add the following lifecycle
  # directive, which instructs Terraform to update any dependent resources
  # before destroying the machine - in the case of applications this means
  # that application units get removed from units before Terraform attempts
  # to destroy the machine.
  lifecycle {
    create_before_destroy = true
  }

}
 resource "juju_application" "k8s_worker" {
  name       = "k8s-worker"
  model_uuid = juju_model.k8s.uuid

  charm {
    name    = "k8s-worker"
    channel = "1.32/stable"
    base    = "ubuntu@22.04"
  }

  machines = [for m in juju_machine.workers : m.machine_id]

  endpoint_bindings = [
       { space = "oam-mgmt" },
       { endpoint = "cluster", space = "data-wld" },
       { endpoint = "containerd",  space = "data-wld" }
  ]
}

```

### Reproduce / Test

```shell
# deploy the juju model with 2 worker machines (run terraform apply). Terraform will create 2 machine resources and will deploy k8s-worker on them
# remove one ip from the var.K8S_WORKER array
# run teraform apply again.erraform will attempt destroying one ip
# Terraform will try destroying the machine but will get stuck and eventually timeout.... even though I put create_before_desttroy = true
```

### Debug/Panic Output

```shell
ℹ️  Partial Terraform Apply (model + k8s machine)...
juju_model.k8s: Refreshing state... [id=e059b083-a86d-4e02-87ff-cb0e3084a933]
juju_machine.control_plane[0]: Refreshing state... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:0:machine-0]
juju_machine.control_plane[1]: Refreshing state... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:4:machine-4]
juju_machine.control_plane[2]: Refreshing state... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:2:machine-2]
juju_machine.workers[1]: Refreshing state... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:3:machine-3]
juju_machine.workers[0]: Refreshing state... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:1:machine-1]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  - destroy

Terraform will perform the following actions:

  # juju_machine.workers[1] will be destroyed
  # (because index [1] is out of range for count)
  - resource "juju_machine" "workers" {
      - base             = "ubuntu@22.04" -> null
      - hostname         = "rsg-o-regt0-mk8s-test1-cl02-w2" -> null
      - id               = "e059b083-a86d-4e02-87ff-cb0e3084a933:3:machine-3" -> null
      - machine_id       = "3" -> null
      - model_uuid       = "e059b083-a86d-4e02-87ff-cb0e3084a933" -> null
      - name             = "machine-3" -> null
      - private_key_file = "/home/ubuntu/.ssh/id_rsa" -> null
      - public_key_file  = "/home/ubuntu/.ssh/id_rsa.pub" -> null
      - ssh_address      = "ubuntu@100.86.128.57" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.
juju_machine.workers[1]: Destroying... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:3:machine-3]
juju_machine.workers[1]: Still destroying... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:3:machine-3, 10s elapsed]
juju_machine.workers[1]: Still destroying... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:3:machine-3, 20s elapsed]
[...]
juju_machine.workers[1]: Still destroying... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:3:machine-3, 13m50s elapsed]
juju_machine.workers[1]: Still destroying... [id=e059b083-a86d-4e02-87ff-cb0e3084a933:3:machine-3, 14m0s elapsed]
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes
│ requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the
│ output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from
│ errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Wait Error
│
│ Timeout reached waiting for machine "3" deletion, got error: max duration exceeded: retrying: no error returned.
│ Make sure no application units or containers are still running on the machine
╵

```

### Notes & References

_No response_

### PR DESCRIPTION
**Pull request by SimoneDutto**
## Description

a machine cannot be removed without --force if it has units assigned to it. So before removing a machine we have to remove the associated units to it.

Read here for more details: https://github.com/juju/terraform-provider-juju/issues/1189#issuecomment-4313569212

Fix: #1189

### CODE REVIEW

**Review by luci1900 — APPROVED** [review]

File: internal/juju/applications.go [hunk 1]
```diff
@@ -1539,7 +1539,9 @@ func (c applicationsClient) removeUnits(input *UpdateApplicationInput, client Ap
 		for _, machine := range input.RemoveMachines {
 			unitName, ok := machineUnits[machine]
 			if !ok {
-				return fmt.Errorf("no machines deployed on machine: %v", machine)
```
Comment (mostafaCamel) [inline internal/juju/applications.go:1542]: Thanks @SimoneDutto  for your PR. Your code and comments made me understand the logic of the codebase just by reading them

I still don't understand the dependency graph behavior which is forcing us to "uncatch" this error. 

Why is terraform trying first to destroy the juju_machine before updating in-place the juju_application (whose `machines` array clearly depends on the juju_machine) ?

Comment (mostafaCamel) [reply internal/juju/applications.go:1542]: Added some comments in the issue about the dependency graph bheavior.

Unless we implement a `juju_unit` resource (probably a breaking api change), Simone's change is the best that can be done.

Can we add though a debug log line here that the unit does not exist because it was likely removed during machine removal?

Comment (SimoneDutto) [reply internal/juju/applications.go:1542]: we have no plans of adding the juju_unit, because it would entail some special case for CAAS deployment.

I'll add the debug log, thanks for the feedback

**Review by ale8k — APPROVED** [review]
lgtm. nice!
