### PR TITLE
[JUJU-2356] Additional checks when comparing config values.

### LINKED ISSUE #121: integers in juju config always show diff in `terraform plan`
### Terraform Version
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.4.3

### Affected Resource(s)
- juju_application

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.4.3"
    }
  }
}
provider "juju" {}

resource "juju_model" "development" {
  name = "nginx-test"

}

resource "juju_application" "nginx" {
  name = "nginx-ingress-integrator"

  model = juju_model.development.name

  charm {
    name     = "nginx-ingress-integrator"
  }

  config = {
    limit-rps = 10
  }
}
```

### Debug Output
```
Terraform will perform the following actions:

  # juju_application.nginx will be updated in-place
  ~ resource "juju_application" "nginx" {
      ~ config = {
          ~ "limit-rps" = "%!s(float64=10)" -> "10"
        }
```
I've tried this with either a string "10" or 10 in my terraform config and it still shows similar output.

### Panic Output
N/A

### Expected Behavior
If you set a config value to an integer that matches the environment it shouldn't show as a difference in `terraform plan`.

### Actual Behavior
See above.

### Steps to Reproduce
See above

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
Due to a limitation in the terraform schema definition, we can only use strings for configuration values. This limits us to treat everything as a string when the configuration values in Juju can have several types (int, bool, float, string). Additional, conversion has to be done between the terraform schema values and the values returned from Juju to ensure that we are comparing the same data type (e.g.: string vs string, int vs int, etc.)

Fix #121 

## QA
Add a model and deploy `ngingx` with some configuration parameters.
```bash
juju add-model nginx-test
juju deploy nginx-ingress-integrator --config limit-rps=10 --config service-hostname="myhostname" --config rewrite-enabled=false
```

Import the model and deployment into the following plan:

```terraform
provider "juju" {}

resource "juju_model" "development" {
  name = "nginx-test"
}

resource "juju_application" "nginx" {
  name = "nginx-ingress-integrator"
  model = juju_model.development.name

  charm {
    name = "nginx-ingress-integrator"
  }

  config = {
    limit-rps = 10
    service-hostname = "myhostname"
    rewrite-enabled = false
  }
}
```
```bash
terraform import juju_model.development nginx-test
terraform import juju_application.nginx nginx-test:nginx-ingress-integrator
```
The terraform plan should not display any change regarding configuration values. Additionally, modify the three configuration parameters, refresh and check they are planned to be modified.

```bash
juju config nginx-ingress-integrator limit-rps=33 service-hostname=changedhostname rewrite-enabled=true
terraform refresh
terraform plan
```

### CODE REVIEW

File: internal/juju/applications.go [hunk 1]
```diff
@@ -466,36 +509,31 @@ func (c applicationsClient) ReadApplication(input *ReadApplicationInput) (*ReadA
...
 			aux := v.(map[string]interface{})
-			isDefault, found := aux["source"]
-			if found && isDefault != "default" {
-				if value, found := aux["value"]; found {
-					conf[k] = fmt.Sprintf("%s", value)
+			if value, found := aux["value"]; found {
+				conf[k] = ConfigEntry{
+					Value:     value,
+					IsDefault: aux["source"] == "default",
 				}
```
Comment (cderici) [inline internal/juju/applications.go:537]: I may be missing something here, but for some config keys won't the CharmConfig will overwrite the `conf[k]` here (that already has the value coming from ApplicationConfig)?

**Review by cderici — APPROVED** [review]
LGTM. QA steps work well :+1:

File: internal/juju/applications.go (hunk 1 above)
Comment (juanmanuel-tirado) [reply internal/juju/applications.go:537]: Yes. This will happen for example if we import the application from an existing deployment.
