### PR TITLE
[JUJU-1969] Fix channel during imports

### LINKED ISSUE #95: After `terraform import` the charm channel isn't correctly recognised
### Terraform Version
```
$ terraform -v
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/juju/juju v0.4.1
```

### Affected Resource(s)

I'm not quite sure, but it affects `terraform import` of a `juju_application` resource.

### Terraform Configuration Files

```
resource "juju_application" "redis_cache" {
  name  = "redis-cache2"
  model = juju_model.staging.name

  charm {
    name = "redis-k8s"
    channel = "edge"
  }

  units = 1
}
```

### Debug Output
Here's my `juju status` output confirming the redis-cache2 application is using the edge channel already:
```
$ juju status redis-cache2
Model       Controller          Cloud/Region        Version  SLA          Timestamp
stg-events  microk8s-localhost  microk8s/localhost  2.9.34   unsupported  11:27:21+02:00

App           Version  Status  Scale  Charm      Channel  Rev  Address         Exposed  Message
redis-cache2  7.0.4    active      1  redis-k8s  edge      18  10.152.183.133  no       

Unit             Workload  Agent  Address       Ports  Message
redis-cache2/0*  active    idle   10.1.129.145         
```
I ran the following:
```
terraform import juju_application.redis_cache stg-events:redis-cache2
```
This reported a successful output. However, when running `terraform plan` I see:
```
  # juju_application.redis_cache will be updated in-place
  ~ resource "juju_application" "redis_cache" {
        id     = "stg-events:redis-cache2"
        name   = "redis-cache2"
        # (4 unchanged attributes hidden)

      ~ charm {
          ~ channel  = "latest/stable" -> "edge"
            name     = "redis-k8s"
            # (2 unchanged attributes hidden)
        }
    }
```
### Panic Output
N/A

### Expected Behavior
This should recognise something is deployed with the channel specified in the terraform configs.

### Actual Behavior
It says it's going to switch it from the stable channel to the edge channel.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `juju deploy redis-k8s --channel=edge`
2. `terraform import` (with relevant application name)
3. Check the output of `terraform plan`.

### Important Factoids
N/A

### References
N/A

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
During the import operation the `channel` attribute for charms was ignored. It looks like a hardcoded `latest/stable` value remained there. In this change, we obtain the channel from the response as done with the other fields. This should fix #95.  

Following the example mentioned at #95, you can use these steps for testing.

Compile the terraform provider and make it available as usual. 
```sh
 $ go build
 $ cp terraform-provider-juju <path-to-terraform>/.terraform.d/plugins/registry.terraform.io/juju/juju/0.4.1/linux_amd64/terraform-provider-juju_v0.4.1
 $ cd <path-to-wherever-you-put-the demo.tf>
```

Using microk8s create a model and a redis deployment.

```bash
juju add-model newmodel
juju deploy redis-k8s --channel=edge -m newmodel
```
Use the following terraform plan:
```terraform
terraform {
   required_providers {
     juju = {
       source  = "juju/juju"
       version = "0.4.1"
     }
  }
}

provider "juju" {}

resource "juju_model" "development" {
  name = "newmodel"
}

resource "juju_application" "redis_cache" {
  name  = "redis-cache2"
  model = juju_model.development.name

  charm {
    name    = "redis-k8s"
    channel = "edge"
  }

  units = 1
}
```
Initialize a terraform environment and import the redis application.

```sh
terraform init
terraform import juju_application.redis_cache newmodel:redis-k8
```
Now the plan should not indicate any changes in the channel attribute:
```sh
terraform plan
....
# juju_application.redis_cache must be replaced
-/+ resource "juju_application" "redis_cache" {
      - config = {} -> null
      ~ id     = "newmodel:redis-k8s" -> (known after apply)
      ~ name   = "redis-k8s" -> "redis-cache2" # forces replacement
        # (3 unchanged attributes hidden)

      ~ charm {
            name     = "redis-k8s"
          ~ revision = 19 -> (known after apply)
          ~ series   = "focal" -> (known after apply)
            # (1 unchanged attribute hidden)
        }
    }

  # juju_model.development will be created
  + resource "juju_model" "development" {
      + id   = (known after apply)
      + name = "newmodel"
      + type = (known after apply)

      + cloud {
          + name   = (known after apply)
          + region = (known after apply)
        }
    }
```

### CODE REVIEW

File: internal/provider/resource_application.go [hunk 1]
```diff
@@ -222,10 +222,6 @@ func resourceApplicationRead(ctx context.Context, d *schema.ResourceData, meta i
 		return nil
 	}
 
-	// TODO: This is a temporary fix to preserve the defined charm channel, as we cannot currently pull this from the API
-	// The if exists statement is also required to allow import to function when no exiting data is in the state
-	// Remove these lines and uncomment under the next TODO
-
 	var charmList map[string]interface{}
 	_, exists := d.GetOk("charm")
 	if exists {
```
Comment (mthaddon) [inline internal/provider/resource_application.go:227]: Do we not also need to specify `charmList["channel"] = response.Channel` here? If I'm understanding it correctly this would happen if someone changes a channel outside of terraform but the application is already in terraform state and they're doing an import.

Comment (juanmanuel-tirado) [reply internal/provider/resource_application.go:227]: You're right.
